import { Issue } from '../types';

export const INITIAL_ISSUES: Issue[] = [
  {
    id: 'iss-101',
    title: 'Severe Pothole Cluster on Outer Ring Road near Connaught Place',
    description: 'Deep road cavity and fractured tarmac along the arterial road near Minto Bridge underpass. Multiple two-wheelers have skidded during evening peak hours.',
    category: 'Damaged Roads & Potholes',
    latitude: 28.6289,
    longitude: 77.2065,
    image_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1200&q=80',
    ai_summary: 'Major road depression and crumbling asphalt creating immediate skidding hazard for commuter two-wheelers on high-traffic corridor.',
    ai_severity: 'High',
    ai_severity_reason: 'Deep road defect on primary arterial transit route posing immediate vehicular safety hazard.',
    status: 'Reported',
    upvote_count: 2,
    reporter_id: 'user-demo-citizen',
    reporter_name: 'Priya Sharma (Connaught Ward)',
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: 'iss-102',
    title: 'BWSSB Main Pipeline Rupture on 100 Feet Road, Indiranagar',
    description: 'Fresh municipal drinking water pipeline burst at the 12th Main junction, Indiranagar, Bengaluru. Water flooding the pedestrian sidewalk for over 6 hours.',
    category: 'Water Leakage',
    latitude: 12.9784,
    longitude: 77.6408,
    image_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f8?auto=format&fit=crop&w=1200&q=80',
    ai_summary: 'Subterranean municipal drinking supply pipeline rupture discharging clean water across pedestrian sidewalk.',
    ai_severity: 'High',
    ai_severity_reason: 'Continuous potable water loss combined with pedestrian path flooding and pavement erosion.',
    status: 'In Progress',
    upvote_count: 3,
    reporter_id: 'user-demo-citizen-2',
    reporter_name: 'Ananya Iyer (Indiranagar Residents)',
    created_at: new Date(Date.now() - 3600000 * 42).toISOString(),
  },
  {
    id: 'iss-103',
    title: 'Overflowing Municipal Waste Vats near Dadar Flower Market',
    description: 'Commercial garbage accumulation behind Dadar West railway station market. Stray cattle and odor affecting pedestrians and local commuters.',
    category: 'Garbage Accumulation',
    latitude: 19.0178,
    longitude: 72.8478,
    image_url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=1200&q=80',
    ai_summary: 'Uncleared municipal refuse bins overflowing with commercial organic waste near transit station footpath.',
    ai_severity: 'Medium',
    ai_severity_reason: 'Sanitary and hygiene concern requiring scheduled BMC waste clearance truck dispatch.',
    status: 'Reported',
    upvote_count: 1,
    reporter_id: 'user-demo-citizen',
    reporter_name: 'Priya Sharma (Connaught Ward)',
    created_at: new Date(Date.now() - 3600000 * 28).toISOString(),
  },
  {
    id: 'iss-104',
    title: 'Four Non-Functional LED Streetlights on Sector 18 Metro Feeder',
    description: 'Consecutive streetlights are dead along the commuter walkway connecting Sector 18 Metro Station and residential blocks in Noida. Extremely dark at night.',
    category: 'Broken Streetlights',
    latitude: 28.5708,
    longitude: 77.3260,
    image_url: 'https://images.unsplash.com/photo-1508873696983-2df5703bc20d?auto=format&fit=crop&w=1200&q=80',
    ai_summary: 'Multiple pole streetlights dark on primary metro commuter path resulting in poor nighttime visibility.',
    ai_severity: 'Medium',
    ai_severity_reason: 'Public safety hazard for night pedestrian commuters requiring electrical inspection.',
    status: 'In Progress',
    upvote_count: 2,
    reporter_id: 'user-demo-citizen-3',
    reporter_name: 'Rohan Mehta (Sector 18)',
    created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
  {
    id: 'iss-105',
    title: 'Broken Stormwater Drain Slab near Anna Nagar Roundtana',
    description: 'Heavy precast concrete drain cover cracked and fallen into the stormwater canal. Poses extreme fall hazard for pedestrians and bus passengers.',
    category: 'Drainage & Sewage',
    latitude: 13.0850,
    longitude: 80.2101,
    image_url: 'https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=1200&q=80',
    ai_summary: 'Damaged stormwater drain slab exposing open culvert hole immediately adjacent to bus boarding bay.',
    ai_severity: 'High',
    ai_severity_reason: 'Uncovered deep drainage hole in heavy foot-traffic area with high fall risk.',
    status: 'Resolved',
    upvote_count: 4,
    reporter_id: 'user-demo-citizen-4',
    reporter_name: 'Karthik Subramanian (Chennai Central)',
    created_at: new Date(Date.now() - 3600000 * 120).toISOString(),
  },
  {
    id: 'iss-106',
    title: 'Faded Zebra Crossing on FC Road outside Campus Gate',
    description: 'Pedestrian zebra crossing stripes on Fergusson College Road have faded completely. Vehicles and buses do not slow down for crossing students.',
    category: 'Public Safety / Other',
    latitude: 18.5204,
    longitude: 73.8408,
    image_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=1200&q=80',
    ai_summary: 'Worn reflective pedestrian zebra paint requiring municipal repainting outside educational campus.',
    ai_severity: 'Low',
    ai_severity_reason: 'Road marking maintenance required to safeguard crossing students and seniors.',
    status: 'Resolved',
    upvote_count: 2,
    reporter_id: 'user-demo-citizen-2',
    reporter_name: 'Ananya Iyer (Indiranagar Residents)',
    created_at: new Date(Date.now() - 3600000 * 150).toISOString(),
  },
];
